export const mockMovies =[

  {
    id: 634649,
    title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker seeks Doctor Strange's help to make the world forget he is Spider-Man. Things go wrong, opening the multiverse.",
    release_date: "2021-12-15",
    vote_average: 8.3,
    vote_count: 16932,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre_ids: [28, 12, 878],
    popularity: 5000.2,
  },
  {
    id: 76600,
    title: "Avatar: The Way of Water",
    overview:
      "Jake Sully lives with his newfound family on Pandora. A familiar threat returns, forcing Jake to fight a difficult war.",
    release_date: "2022-12-14",
    vote_average: 7.7,
    vote_count: 9100,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    genre_ids: [878, 12, 28],
    popularity: 4500.8,
  },
  {
    id: 575264,
    title: "Mission: Impossible - Dead Reckoning Part One",
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: to track down a terrifying new weapon.",
    release_date: "2023-07-08",
    vote_average: 7.5,
    vote_count: 3800,
    poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    backdrop_path: "/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg",
    genre_ids: [28, 53],
    popularity: 3200.5,
  },
  {
    id: 385687,
    title: "Fast X",
    overview:
      "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
    release_date: "2023-05-17",
    vote_average: 7.1,
    vote_count: 2900,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    backdrop_path: "/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg",
    genre_ids: [28, 80, 53],
    popularity: 2700.6,
  },
  {
    id: 667538,
    title: "Transformers: Rise of the Beasts",
    overview:
      "A '90s globetrotting adventure with the Autobots and Maximals as they join forces against a new threat.",
    release_date: "2023-06-06",
    vote_average: 7.2,
    vote_count: 2600,
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    backdrop_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
    genre_ids: [28, 12, 878],
    popularity: 2300.9,
  },
  {
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    overview:
      "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T’Challa.",
    release_date: "2022-11-09",
    vote_average: 7.1,
    vote_count: 7600,
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    genre_ids: [28, 12, 878],
    popularity: 4200.3,
  },
  {
    id: 298618,
    title: "The Flash",
    overview:
      "Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without superheroes.",
    release_date: "2023-06-13",
    vote_average: 6.9,
    vote_count: 3400,
    poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    backdrop_path: "/zEqwfO5R2LrrLgV61xm8M9TmNTG.jpg",
    genre_ids: [28, 12, 878],
    popularity: 2100.7,
  },
  {
    id: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    overview:
      "The Guardians rally together to defend the universe while dealing with Rocket's mysterious past.",
    release_date: "2023-05-03",
    vote_average: 8.0,
    vote_count: 8500,
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    genre_ids: [28, 12, 878],
    popularity: 3800.4,
  },
  {
    id: 639933,
    title: "The Batman",
    overview:
      "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
    release_date: "2022-03-01",
    vote_average: 7.8,
    vote_count: 12000,
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop_path: "/qHZ3GyNclt8tL6Mt82spvTvfmgP.jpg",
    genre_ids: [80, 9648, 53],
    popularity: 4000.1,
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives.",
    release_date: "2022-12-07",
    vote_average: 8.4,
    vote_count: 6500,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [16, 12, 35],
    popularity: 3700.6,
  },
];
